spring.application.name=BloggingSystem
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${MARIADB_DATASOURCE_URL}
spring.datasource.username=${MARIADB_USERNAME}
spring.datasource.password=${MARIADB_PASSWORD}

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG