spring.application.name=BloggingSystem
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${MARIADB_DATASOURCE_URL}
spring.datasource.username=${MARIADB_USERNAME}
spring.datasource.password=${MARIADB_PASSWORD}

aws.region=us-east-1
aws.s3.bucket=portfolio-blog-uploads
aws.s3.cdn-url=https://cdn.shawnosborne.dev

##--600,000ms = 600sec = 10min
spring.datasource.hikari.max-lifetime=595000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.maximum-pool-size=9
spring.datasource.hikari.minimum-idle=1

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shawns.portfolio.blog@gmail.com
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.web.error.path=/error

## if a state changing request happens after expiration, re-directs to /blog?sessionExpired and inform user to log in again.
server.servlet.session.timeout=60m
server.compression.enabled=true
server.compression.mime-types=text/html
server.compression.min-response-size=2048
