spring.application.name=BloggingSystem
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${MYSQL_DATASOURCE_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

logging.level.org.hibernate.SQL=debug

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

# need to generate keypair at least 2048
# openssl genrsa -out keypair.pem 2048
#
## extract public key
# openssl rsa -in keypair.pem -pubout -out public.pem
#
## create private key in PKCS#8 format
# openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in keypair.pem -out private.pem
## no need for keypair.pem after these operations complete

# private.pem should be kept secret and stored externally in some type of Key Management service.
# I will probably use AWS Secrets Manager.
# todo : figure out how to retrieve private key from an external source.
rsa.private-key=classpath:certs/private.pem

rsa.public-key=classpath:certs/public.pem
